---
- name: Validar sistema operacional suportado
  ansible.builtin.assert:
    that:
      - ansible_system == "Linux"
    fail_msg: "Este playbook foi preparado para Linux/WSL."

- name: Instalar dependÃªncias base
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - ca-certificates
      - gnupg
      - lsb-release
      - tar
    state: present
    update_cache: true
